// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpMwLu9ZcAEXATf6Yi3-PPXyP2qpr_AmA',
    appId: '1:972181163248:web:9c5818dc6b5bc94f6d0635',
    messagingSenderId: '972181163248',
    projectId: 'refugio-calor-mxl',
    authDomain: 'refugio-calor-mxl.firebaseapp.com',
    storageBucket: 'refugio-calor-mxl.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhhnVr-HpCG66-BmQlUCrVDefbTHpMy44',
    appId: '1:972181163248:android:6e9ab1ffaafcbe506d0635',
    messagingSenderId: '972181163248',
    projectId: 'refugio-calor-mxl',
    storageBucket: 'refugio-calor-mxl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5dqM_-qJE_aq5Tvl1SdvginhOuvnbz1M',
    appId: '1:972181163248:ios:0ec1c4b7751424c96d0635',
    messagingSenderId: '972181163248',
    projectId: 'refugio-calor-mxl',
    storageBucket: 'refugio-calor-mxl.firebasestorage.app',
    iosBundleId: 'com.example.refugioCalor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5dqM_-qJE_aq5Tvl1SdvginhOuvnbz1M',
    appId: '1:972181163248:ios:0ec1c4b7751424c96d0635',
    messagingSenderId: '972181163248',
    projectId: 'refugio-calor-mxl',
    storageBucket: 'refugio-calor-mxl.firebasestorage.app',
    iosBundleId: 'com.example.refugioCalor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpMwLu9ZcAEXATf6Yi3-PPXyP2qpr_AmA',
    appId: '1:972181163248:web:53a9851e136ede866d0635',
    messagingSenderId: '972181163248',
    projectId: 'refugio-calor-mxl',
    authDomain: 'refugio-calor-mxl.firebaseapp.com',
    storageBucket: 'refugio-calor-mxl.firebasestorage.app',
  );
}
